### ISSUE TITLE
Display suggestions

### ISSUE THREAD

**Issue by keiranmraine** [cmdcolin/ga4ghviewer#1]
Hi, having a dig through the plugins to see if any are of interest to our users and had some thoughts:
- The GA4GH names are basically noise
  - `compact` view by default?
  - under `normal` turn off names by default?
- Switch to density plot above a threshold (~10kb per/tile)
- Disable once tile exceeds ~25kb

Cheers,
K

**Comment by cmdcolin** [comment]
Very true!

I have been thinking making an interesting visualization of the data would be nice. I always thought the HapMap GBrowse is a really cool project too http://hapmap.ncbi.nlm.nih.gov/cgi-perl/gbrowse/hapmap28_B36/?name=Chr9%3A660%2C000..760%2C000 would be nice to take a note from their group for jbrowse

I'll see if I can add some of those configs to the demo though!

**Comment by cmdcolin** [comment]
Switched to the ensembl GA4GH server which has better names. I think this plugin is basically just a "store" adapter so display configurations are up to user, but things like featureScale can help disable after certain point.

**Comment by cmdcolin** [comment]
The 1kg server is still supported but basically ensembl's rest api supported https so has higher compatibility :)
