### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by enuggetry** [cmdcolin/ga4ghviewer#2]
I couldn't get the demo working.

**Comment by cmdcolin** [comment]
Any details on setup or error msgs? The demo at http://cmdcolin.github.io/jbrowse/?loc=chr1%3A83766889..83767617&tracks=GA4GH%201kg%20(functional%20annot)%2CGA4GH%201kg%20(phase3)&highlight= is still working

**Comment by enuggetry** [comment]
The GA4GH tracks were not loading - showing Loading message.
I forgot to note the console message.
They appear to be working now, though.

**Comment by cmdcolin** [comment]
If you're zoomed out too far it'll try and download too much data and load for a while. If we can implement the getGlobalStats function on the store class it might be able to suggest Too much data more intelligently
